export const SUPPORTED_LOCALES = ['zh-CN', 'en', 'ja', 'ko', 'es', 'pt-BR', 'fr', 'de'];

export const translations = {
  en: {
    navGames: 'Games', navAbout: 'About', navAll: 'All games', navHow: 'How to play', navBoard: 'Endless board', navMain: 'Main navigation', navLanguage: 'Site language', themeDay: '☀ Day', themeNight: '☾ Night',
    homeTitleMeta: 'KNOWHY GAMES · Independent games', homeDescriptionMeta: 'Discover independent games from KNOWHY GAMES. Meet Classroom Snacks and choose where to play.',
    homeEyebrow: 'KNOWHY GAMES / A small game studio', homeTitle: 'Small games. Big moments.', homeLead: 'A growing collection of playful worlds. Find a game, learn its story, and choose where to play.', homeExplore: 'Explore games ↓', homeArtCaption: 'Featured: Classroom Snacks',
    gamesKicker: 'THE COLLECTION', gamesTitle: 'Explore the collection', gameTag: 'Solo · light strategy · playtest', gameTitle: 'Classroom Snacks', gameDescription: 'The bell rings. The teacher patrols. Pick your snack, wait for an opening, and put it away before they turn around.', gameMore: 'See the game →', catalogNote: 'More KNOWHY games will join the collection. Each will have its own story and play links.',
    aboutKicker: 'ABOUT THE SITE', aboutTitle: 'A home for our games.', aboutBody: 'Explore each game here, then follow its platform link to play. This site is a catalog, not a playable game host.', footerBack: 'Back to KNOWHY', homeImageAlt: 'Classroom Snacks illustrated classroom scene with a child sneaking food',
    detailTitleMeta: 'Classroom Snacks · KNOWHY GAMES', detailDescriptionMeta: 'How to play Classroom Snacks, its game modes, and where to play.',
    detailBack: '← All games', detailEyebrow: 'Independent game · playtest', detailTitle: 'Classroom Snacks', detailLead: 'The teacher turns away. This is your chance. Pick a snack, take a bite, and hide it before they look back.', detailTagSolo: 'Solo strategy', detailTagFour: 'Four difficulties', detailTagModes: 'Timed / endless', detailPlay: 'Play on itch.io ↗', detailPlatform: 'The game opens on itch.io; this site shares its story and play details.', detailImageAlt: 'Gameplay screenshot of the Classroom Snacks classroom', detailImageCaption: 'Actual gameplay',
    howKicker: 'HOW TO PLAY', howTitle: 'One snack at a time.', stepOneTitle: 'Pick a snack', stepOneBody: 'Each snack takes a different time to eat and gives a different amount of fullness and points.', stepTwoTitle: 'Wait for an opening', stepTwoBody: 'Watch where the teacher stands and faces. You can stop eating halfway through.', stepThreeTitle: 'Hide it in time', stepThreeBody: 'In timed mode, reach the fullness goal and last until the bell rings.',
    modesKicker: 'TWO WAYS TO PLAY', modesTitle: 'Finish the class or chase a record.', timedTitle: 'Timed challenge', timedBody: 'Fill up before class ends and make it through the round.', endlessTitle: 'Endless challenge', endlessBody: 'No class timer and no snack limit. How high can you score?', modesFoot: 'Both modes have four difficulties. Personal records are saved separately.',
    boardKicker: 'PLAYTEST LEADERBOARD', boardTitle: 'Endless rankings', boardIntro: 'Each difficulty has its own ranking. Only scores players choose to share appear here.', boardDisclaimer: 'Top 20 per difficulty. Playtest scores are not verified against cheating.', tierNormal: 'Normal', tierAdvanced: 'Advanced', tierHard: 'Hard', tierHell: 'Hell', boardPanel: 'ENDLESS', boardTop20: 'TOP 20', boardRank: 'Rank', boardPlayer: 'Player', boardScore: 'Score', boardLoading: 'Loading rankings…', boardOffline: 'Rankings are not connected. Places remain open.', boardEmpty: 'No ranked scores yet. The first places are open.', boardError: 'Rankings are unavailable right now. Places remain open.', boardCount: '{count} players ranked', footerAll: 'All games'
  },
  'zh-CN': {
    navGames: '游戏作品', navAbout: '关于', navAll: '所有游戏', navHow: '玩法', navBoard: '无尽榜单', navMain: '主导航', navLanguage: '网站语言', themeDay: '☀ 白天', themeNight: '☾ 夜晚',
    homeTitleMeta: 'KNOWHY GAMES · 游戏作品', homeDescriptionMeta: '认识 KNOWHY GAMES 的独立游戏作品，了解《课堂偷吃》并选择游戏平台。',
    homeEyebrow: 'KNOWHY GAMES / 小游戏工作室', homeTitle: '小小一局，玩出大动静。', homeLead: '这里收藏不断生长的有趣世界。选一款游戏，了解它的故事，再挑一个地方开始玩。', homeExplore: '看看游戏 ↓', homeArtCaption: '本期作品 · 课堂偷吃',
    gamesKicker: '游戏作品', gamesTitle: '探索游戏目录', gameTag: '单人 · 轻策略 · 试玩中', gameTitle: '课堂偷吃', gameDescription: '铃声响起，老师开始巡逻。挑零食、抓空档、及时收手，别让老师发现。', gameMore: '查看游戏详情 →', catalogNote: '今后有新作品，也会加入这里；每款游戏都有自己的介绍和游玩入口。',
    aboutKicker: '关于本站', aboutTitle: '这里收着我们的游戏。', aboutBody: '在这里了解作品，再通过对应平台游玩。本站是游戏目录，不直接提供在线游戏。', footerBack: '返回 KNOWHY', homeImageAlt: '《课堂偷吃》插画：学生在教室里偷偷吃零食',
    detailTitleMeta: '课堂偷吃 · KNOWHY GAMES', detailDescriptionMeta: '了解《课堂偷吃》的玩法、模式和游玩入口。',
    detailBack: '← 所有游戏', detailEyebrow: '独立游戏 · 试玩中', detailTitle: '课堂偷吃', detailLead: '老师一转身，机会就来了。挑好零食，抓住空档吃一口；他回头时，记得及时收起来。', detailTagSolo: '单人轻策略', detailTagFour: '四档难度', detailTagModes: '限时 / 无尽', detailPlay: '前往 itch.io 游玩 ↗', detailPlatform: '游戏将在 itch.io 打开；本站只介绍作品和玩法。', detailImageAlt: '《课堂偷吃》的教室游玩画面', detailImageCaption: '游戏内实机画面',
    howKicker: '玩法', howTitle: '这一局，怎么偷吃？', stepOneTitle: '选一份零食', stepOneBody: '不同零食的进食时间、饱腹和积分各不相同。', stepTwoTitle: '等个空档开吃', stepTwoBody: '留意老师的位置和朝向；吃到一半也可以停。', stepThreeTitle: '老师回头就收手', stepThreeBody: '限时模式下达到饱腹目标，并坚持到下课铃响。',
    modesKicker: '两种玩法', modesTitle: '想通关，还是想冲分？', timedTitle: '限时挑战', timedBody: '下课前达到饱腹目标，守住这一局。', endlessTitle: '无尽挑战', endlessBody: '没有下课倒计时，也不会吃光零食；目标是积累更多分数。', modesFoot: '两种玩法各有四档难度；本地纪录分开保存。',
    boardKicker: '试玩榜单', boardTitle: '无尽模式积分榜', boardIntro: '四档独立排名，仅显示玩家自愿提交的成绩。', boardDisclaimer: '各难度最多展示前 20 名；试玩成绩尚未经过防作弊验证。', tierNormal: '普通', tierAdvanced: '复杂', tierHard: '困难', tierHell: '地狱', boardPanel: '无尽', boardTop20: '前 20 名', boardRank: '名次', boardPlayer: '玩家', boardScore: '积分', boardLoading: '正在读取榜单…', boardOffline: '榜单服务尚未接通，名次席位暂时空着。', boardEmpty: '暂无上榜成绩，前排席位等你来占。', boardError: '暂时无法读取榜单，名次席位暂时空着。', boardCount: '当前已上榜 {count} 位', footerAll: '全部游戏'
  },
  ja: {
    navGames: 'ゲーム', navAbout: 'サイトについて', navAll: '全ゲーム', navHow: '遊び方', navBoard: 'エンドレス順位', navMain: 'メインナビ', navLanguage: 'サイトの言語', themeDay: '☀ 昼', themeNight: '☾ 夜',
    homeTitleMeta: 'KNOWHY GAMES · インディーゲーム', homeDescriptionMeta: 'KNOWHY GAMES の作品を紹介。Classroom Snacks の遊び方とプレイ先をご覧ください。',
    homeEyebrow: 'KNOWHY GAMES / 小さなゲームスタジオ', homeTitle: '小さなゲーム、大きな瞬間。', homeLead: '遊び心あふれる世界を少しずつ増やしています。気になるゲームを見つけて、遊ぶ場所を選んでください。', homeExplore: 'ゲームを見る ↓', homeArtCaption: '注目作 · Classroom Snacks',
    gamesKicker: '作品一覧', gamesTitle: 'ゲームを探す', gameTag: '一人用 · ライト戦略 · テスト公開中', gameTitle: 'Classroom Snacks', gameDescription: 'チャイムが鳴り、先生が見回りを始める。おやつを選び、隙を見て食べ、振り向く前にしまおう。', gameMore: 'ゲームの詳細を見る →', catalogNote: '新作もここに追加予定。各ゲームに紹介とプレイ先を用意します。',
    aboutKicker: 'このサイトについて', aboutTitle: '私たちのゲームが集まる場所。', aboutBody: 'ここで作品を知り、各プラットフォームからプレイできます。このサイト内ではゲームを配信していません。', footerBack: 'KNOWHY に戻る', homeImageAlt: '教室で子どもがこっそりおやつを食べる Classroom Snacks のイラスト',
    detailTitleMeta: 'Classroom Snacks · KNOWHY GAMES', detailDescriptionMeta: 'Classroom Snacks の遊び方、モード、プレイ先。',
    detailBack: '← 全ゲーム', detailEyebrow: 'インディーゲーム · テスト公開中', detailTitle: 'Classroom Snacks', detailLead: '先生が背を向けたらチャンス。おやつを選んでひと口。こちらを向く前に隠そう。', detailTagSolo: '一人用の軽い戦略', detailTagFour: '4段階の難易度', detailTagModes: '時間制 / エンドレス', detailPlay: 'itch.io でプレイ ↗', detailPlatform: 'ゲームは itch.io で開きます。このサイトでは作品と遊び方を紹介しています。', detailImageAlt: 'Classroom Snacks の教室のプレイ画面', detailImageCaption: '実際のゲーム画面',
    howKicker: '遊び方', howTitle: 'おやつは一つずつ。', stepOneTitle: 'おやつを選ぶ', stepOneBody: '食べる時間、満腹度、得点はおやつによって異なります。', stepTwoTitle: '隙を待つ', stepTwoBody: '先生の位置と向きに注目。途中で食べるのをやめることもできます。', stepThreeTitle: '間に合うように隠す', stepThreeBody: '時間制では満腹目標を達成し、チャイムまで見つからずに過ごそう。',
    modesKicker: '二つの遊び方', modesTitle: 'クリアを狙う？記録に挑む？', timedTitle: '時間制チャレンジ', timedBody: '授業が終わるまでに満腹になり、最後まで切り抜けよう。', endlessTitle: 'エンドレスチャレンジ', endlessBody: '時間制限もおやつの数の制限もなし。どこまで得点を伸ばせる？', modesFoot: 'どちらも難易度は4段階。自己ベストは別々に保存されます。',
    boardKicker: 'テスト順位', boardTitle: 'エンドレス順位表', boardIntro: '難易度ごとに集計。自分で共有したスコアだけが表示されます。', boardDisclaimer: '各難易度上位20名。テストスコアの不正対策は未実施です。', tierNormal: '普通', tierAdvanced: '複雑', tierHard: '難しい', tierHell: '地獄', boardPanel: 'エンドレス', boardTop20: '上位20名', boardRank: '順位', boardPlayer: 'プレイヤー', boardScore: '得点', boardLoading: '順位を読み込み中…', boardOffline: '順位サービスは未接続です。枠は空けてあります。', boardEmpty: 'まだ記録がありません。最初の枠を目指そう。', boardError: '現在順位を読み込めません。枠は空けてあります。', boardCount: '{count} 人がランクイン', footerAll: '全ゲーム'
  },
  ko: {
    navGames: '게임', navAbout: '소개', navAll: '모든 게임', navHow: '플레이 방법', navBoard: '무한 순위', navMain: '주 메뉴', navLanguage: '사이트 언어', themeDay: '☀ 낮', themeNight: '☾ 밤',
    homeTitleMeta: 'KNOWHY GAMES · 인디 게임', homeDescriptionMeta: 'KNOWHY GAMES의 작품을 만나고 Classroom Snacks의 플레이 방법과 링크를 확인하세요.',
    homeEyebrow: 'KNOWHY GAMES / 작은 게임 스튜디오', homeTitle: '작은 게임, 큰 순간.', homeLead: '작지만 재미있는 세계가 계속 늘어납니다. 게임을 발견하고 이야기를 읽은 뒤 플레이할 곳을 골라 보세요.', homeExplore: '게임 살펴보기 ↓', homeArtCaption: '대표작 · Classroom Snacks',
    gamesKicker: '게임 목록', gamesTitle: '게임 살펴보기', gameTag: '1인용 · 가벼운 전략 · 테스트 중', gameTitle: 'Classroom Snacks', gameDescription: '종이 울리고 선생님이 순찰을 시작합니다. 간식을 고르고 틈을 노린 뒤 들키기 전에 숨기세요.', gameMore: '게임 자세히 보기 →', catalogNote: '새로운 KNOWHY 게임도 이곳에 추가됩니다. 각 게임마다 소개와 플레이 링크가 있습니다.',
    aboutKicker: '사이트 소개', aboutTitle: '우리 게임이 모이는 곳.', aboutBody: '여기서 게임을 알아보고 각 플랫폼에서 플레이하세요. 이 사이트에서는 게임을 직접 실행하지 않습니다.', footerBack: 'KNOWHY로 돌아가기', homeImageAlt: '교실에서 아이가 몰래 간식을 먹는 Classroom Snacks 일러스트',
    detailTitleMeta: 'Classroom Snacks · KNOWHY GAMES', detailDescriptionMeta: 'Classroom Snacks의 플레이 방법, 모드와 플레이 링크.',
    detailBack: '← 모든 게임', detailEyebrow: '인디 게임 · 테스트 중', detailTitle: 'Classroom Snacks', detailLead: '선생님이 등을 돌리면 기회입니다. 간식을 골라 한입 먹고, 다시 보기 전에 숨기세요.', detailTagSolo: '1인용 전략', detailTagFour: '4단계 난이도', detailTagModes: '시간제 / 무한', detailPlay: 'itch.io에서 플레이 ↗', detailPlatform: '게임은 itch.io에서 열립니다. 이곳에서는 작품과 플레이 방법을 소개합니다.', detailImageAlt: 'Classroom Snacks 교실 플레이 화면', detailImageCaption: '실제 게임 화면',
    howKicker: '플레이 방법', howTitle: '간식은 한 번에 하나씩.', stepOneTitle: '간식 고르기', stepOneBody: '간식마다 먹는 시간, 포만감, 점수가 다릅니다.', stepTwoTitle: '틈 기다리기', stepTwoBody: '선생님의 위치와 방향을 살피세요. 먹는 도중에도 멈출 수 있습니다.', stepThreeTitle: '제때 숨기기', stepThreeBody: '시간제 모드에서는 포만 목표를 채우고 종이 울릴 때까지 버티세요.',
    modesKicker: '두 가지 모드', modesTitle: '수업을 끝낼까, 기록에 도전할까?', timedTitle: '시간제 도전', timedBody: '수업이 끝나기 전에 배를 채우고 끝까지 살아남으세요.', endlessTitle: '무한 도전', endlessBody: '시간 제한도 간식 수 제한도 없습니다. 얼마나 높은 점수를 낼 수 있을까요?', modesFoot: '두 모드 모두 난이도는 4단계이며 개인 최고 기록은 따로 저장됩니다.',
    boardKicker: '테스트 순위', boardTitle: '무한 모드 순위', boardIntro: '난이도별 순위입니다. 플레이어가 공유한 점수만 표시됩니다.', boardDisclaimer: '난이도별 상위 20명. 테스트 점수에는 부정행위 검증이 없습니다.', tierNormal: '보통', tierAdvanced: '복잡', tierHard: '어려움', tierHell: '지옥', boardPanel: '무한', boardTop20: '상위 20명', boardRank: '순위', boardPlayer: '플레이어', boardScore: '점수', boardLoading: '순위 불러오는 중…', boardOffline: '순위 서비스가 연결되지 않았습니다. 빈자리는 유지됩니다.', boardEmpty: '아직 등록된 점수가 없습니다. 첫 자리에 도전하세요.', boardError: '지금은 순위를 불러올 수 없습니다. 빈자리는 유지됩니다.', boardCount: '{count}명 순위 등록', footerAll: '모든 게임'
  },
  es: {
    navGames: 'Juegos', navAbout: 'Acerca de', navAll: 'Todos los juegos', navHow: 'Cómo jugar', navBoard: 'Clasificación infinita', navMain: 'Navegación principal', navLanguage: 'Idioma del sitio', themeDay: '☀ Día', themeNight: '☾ Noche',
    homeTitleMeta: 'KNOWHY GAMES · Juegos independientes', homeDescriptionMeta: 'Descubre los juegos de KNOWHY GAMES. Conoce Classroom Snacks y dónde jugarlo.',
    homeEyebrow: 'KNOWHY GAMES / Pequeño estudio', homeTitle: 'Juegos pequeños. Grandes momentos.', homeLead: 'Una colección creciente de mundos divertidos. Descubre un juego, conoce su historia y elige dónde jugar.', homeExplore: 'Explorar juegos ↓', homeArtCaption: 'Destacado · Classroom Snacks',
    gamesKicker: 'CATÁLOGO', gamesTitle: 'Explora la colección', gameTag: 'Un jugador · estrategia ligera · prueba', gameTitle: 'Classroom Snacks', gameDescription: 'Suena el timbre y el profesor empieza a vigilar. Elige un tentempié, espera tu oportunidad y escóndelo a tiempo.', gameMore: 'Ver el juego →', catalogNote: 'Los próximos juegos de KNOWHY también aparecerán aquí, cada uno con su propia página y enlaces.',
    aboutKicker: 'SOBRE EL SITIO', aboutTitle: 'Un hogar para nuestros juegos.', aboutBody: 'Descubre aquí cada juego y sigue su enlace para jugar en la plataforma correspondiente. Este sitio es un catálogo.', footerBack: 'Volver a KNOWHY', homeImageAlt: 'Ilustración de Classroom Snacks con un niño comiendo a escondidas en clase',
    detailTitleMeta: 'Classroom Snacks · KNOWHY GAMES', detailDescriptionMeta: 'Cómo jugar a Classroom Snacks, sus modos y dónde jugar.',
    detailBack: '← Todos los juegos', detailEyebrow: 'Juego independiente · prueba', detailTitle: 'Classroom Snacks', detailLead: 'El profesor se da la vuelta: es tu oportunidad. Elige un tentempié, da un bocado y escóndelo antes de que mire.', detailTagSolo: 'Estrategia individual', detailTagFour: 'Cuatro dificultades', detailTagModes: 'Contrarreloj / infinito', detailPlay: 'Jugar en itch.io ↗', detailPlatform: 'El juego se abre en itch.io; aquí encontrarás su historia y cómo jugar.', detailImageAlt: 'Captura del aula de Classroom Snacks', detailImageCaption: 'Imagen real del juego',
    howKicker: 'CÓMO JUGAR', howTitle: 'Un bocado cada vez.', stepOneTitle: 'Elige un tentempié', stepOneBody: 'Cada comida tarda un tiempo distinto y da saciedad y puntos diferentes.', stepTwoTitle: 'Espera el momento', stepTwoBody: 'Observa la posición y mirada del profesor. Puedes parar a mitad de bocado.', stepThreeTitle: 'Escóndelo a tiempo', stepThreeBody: 'En el modo contrarreloj, llega al objetivo de saciedad y resiste hasta el timbre.',
    modesKicker: 'DOS MODOS', modesTitle: '¿Terminar la clase o batir un récord?', timedTitle: 'Reto contrarreloj', timedBody: 'Llénate antes de que termine la clase y supera la ronda.', endlessTitle: 'Reto infinito', endlessBody: 'Sin límite de tiempo ni de comida. ¿Cuántos puntos lograrás?', modesFoot: 'Ambos modos tienen cuatro dificultades y récords personales separados.',
    boardKicker: 'CLASIFICACIÓN DE PRUEBA', boardTitle: 'Clasificación infinita', boardIntro: 'Cada dificultad tiene su lista. Solo aparecen las puntuaciones compartidas voluntariamente.', boardDisclaimer: 'Los 20 mejores por dificultad. No se verifica el juego limpio en esta prueba.', tierNormal: 'Normal', tierAdvanced: 'Avanzado', tierHard: 'Difícil', tierHell: 'Infierno', boardPanel: 'INFINITO', boardTop20: '20 MEJORES', boardRank: 'Puesto', boardPlayer: 'Jugador', boardScore: 'Puntos', boardLoading: 'Cargando clasificación…', boardOffline: 'La clasificación no está conectada. Los puestos siguen libres.', boardEmpty: 'Aún no hay puntuaciones. Los primeros puestos están libres.', boardError: 'No se puede cargar la clasificación. Los puestos siguen libres.', boardCount: '{count} jugadores clasificados', footerAll: 'Todos los juegos'
  },
  'pt-BR': {
    navGames: 'Jogos', navAbout: 'Sobre', navAll: 'Todos os jogos', navHow: 'Como jogar', navBoard: 'Ranking infinito', navMain: 'Navegação principal', navLanguage: 'Idioma do site', themeDay: '☀ Dia', themeNight: '☾ Noite',
    homeTitleMeta: 'KNOWHY GAMES · Jogos independentes', homeDescriptionMeta: 'Conheça os jogos da KNOWHY GAMES. Descubra Classroom Snacks e onde jogar.',
    homeEyebrow: 'KNOWHY GAMES / Pequeno estúdio', homeTitle: 'Jogos pequenos. Grandes momentos.', homeLead: 'Uma coleção crescente de mundos divertidos. Encontre um jogo, conheça sua história e escolha onde jogar.', homeExplore: 'Explorar jogos ↓', homeArtCaption: 'Em destaque · Classroom Snacks',
    gamesKicker: 'CATÁLOGO', gamesTitle: 'Explore a coleção', gameTag: 'Solo · estratégia leve · teste', gameTitle: 'Classroom Snacks', gameDescription: 'O sinal toca e o professor começa a vigiar. Escolha um lanche, espere uma brecha e esconda tudo a tempo.', gameMore: 'Ver o jogo →', catalogNote: 'Novos jogos da KNOWHY aparecerão aqui, cada um com sua página e seus links.',
    aboutKicker: 'SOBRE O SITE', aboutTitle: 'Um lugar para nossos jogos.', aboutBody: 'Conheça cada jogo aqui e use o link da plataforma para jogar. Este site é um catálogo, não hospeda os jogos.', footerBack: 'Voltar para KNOWHY', homeImageAlt: 'Ilustração de Classroom Snacks com uma criança comendo escondida na sala de aula',
    detailTitleMeta: 'Classroom Snacks · KNOWHY GAMES', detailDescriptionMeta: 'Como jogar Classroom Snacks, seus modos e onde jogar.',
    detailBack: '← Todos os jogos', detailEyebrow: 'Jogo independente · teste', detailTitle: 'Classroom Snacks', detailLead: 'O professor virou de costas: aproveite. Escolha um lanche, dê uma mordida e esconda antes que ele olhe.', detailTagSolo: 'Estratégia solo', detailTagFour: 'Quatro dificuldades', detailTagModes: 'Cronometrado / infinito', detailPlay: 'Jogar no itch.io ↗', detailPlatform: 'O jogo abre no itch.io; aqui você conhece a história e as regras.', detailImageAlt: 'Captura da sala de aula de Classroom Snacks', detailImageCaption: 'Imagem real do jogo',
    howKicker: 'COMO JOGAR', howTitle: 'Um lanche de cada vez.', stepOneTitle: 'Escolha um lanche', stepOneBody: 'Cada lanche leva um tempo diferente para comer e dá saciedade e pontos distintos.', stepTwoTitle: 'Espere uma brecha', stepTwoBody: 'Observe onde o professor está e para onde olha. Você pode parar no meio.', stepThreeTitle: 'Esconda a tempo', stepThreeBody: 'No modo cronometrado, atinja a meta de saciedade e resista até o sinal.',
    modesKicker: 'DOIS MODOS', modesTitle: 'Vencer a aula ou bater um recorde?', timedTitle: 'Desafio cronometrado', timedBody: 'Fique satisfeito antes de a aula acabar e sobreviva à rodada.', endlessTitle: 'Desafio infinito', endlessBody: 'Sem limite de tempo nem de lanches. Até onde vai sua pontuação?', modesFoot: 'Ambos os modos têm quatro dificuldades e recordes pessoais separados.',
    boardKicker: 'RANKING DE TESTE', boardTitle: 'Ranking infinito', boardIntro: 'Cada dificuldade tem sua lista. Só aparecem pontuações compartilhadas pelos jogadores.', boardDisclaimer: 'Os 20 melhores por dificuldade. Esta versão de teste não verifica trapaças.', tierNormal: 'Normal', tierAdvanced: 'Avançado', tierHard: 'Difícil', tierHell: 'Inferno', boardPanel: 'INFINITO', boardTop20: '20 MELHORES', boardRank: 'Posição', boardPlayer: 'Jogador', boardScore: 'Pontos', boardLoading: 'Carregando ranking…', boardOffline: 'O ranking não está conectado. As posições continuam livres.', boardEmpty: 'Ainda não há pontuações. As primeiras posições estão livres.', boardError: 'Não foi possível carregar o ranking. As posições continuam livres.', boardCount: '{count} jogadores no ranking', footerAll: 'Todos os jogos'
  },
  fr: {
    navGames: 'Jeux', navAbout: 'À propos', navAll: 'Tous les jeux', navHow: 'Comment jouer', navBoard: 'Classement infini', navMain: 'Navigation principale', navLanguage: 'Langue du site', themeDay: '☀ Jour', themeNight: '☾ Nuit',
    homeTitleMeta: 'KNOWHY GAMES · Jeux indépendants', homeDescriptionMeta: 'Découvrez les jeux de KNOWHY GAMES, dont Classroom Snacks, et où y jouer.',
    homeEyebrow: 'KNOWHY GAMES / Petit studio', homeTitle: 'Petits jeux. Grands moments.', homeLead: 'Une collection grandissante de mondes ludiques. Découvrez un jeu, son histoire et où y jouer.', homeExplore: 'Explorer les jeux ↓', homeArtCaption: 'À la une · Classroom Snacks',
    gamesKicker: 'COLLECTION', gamesTitle: 'Explorer la collection', gameTag: 'Solo · stratégie légère · test', gameTitle: 'Classroom Snacks', gameDescription: 'La sonnerie retentit et le professeur patrouille. Choisissez un encas, attendez une ouverture et cachez-le à temps.', gameMore: 'Voir le jeu →', catalogNote: 'Les prochains jeux de KNOWHY rejoindront cette collection, chacun avec sa page et ses liens.',
    aboutKicker: 'À PROPOS DU SITE', aboutTitle: 'Un lieu pour nos jeux.', aboutBody: 'Découvrez chaque jeu ici, puis suivez son lien pour jouer sur la plateforme adaptée. Ce site est un catalogue.', footerBack: 'Retour à KNOWHY', homeImageAlt: 'Illustration de Classroom Snacks avec un enfant qui grignote en cachette en classe',
    detailTitleMeta: 'Classroom Snacks · KNOWHY GAMES', detailDescriptionMeta: 'Règles de Classroom Snacks, modes et lien pour jouer.',
    detailBack: '← Tous les jeux', detailEyebrow: 'Jeu indépendant · test', detailTitle: 'Classroom Snacks', detailLead: 'Le professeur tourne le dos : c’est le moment. Choisissez un encas, prenez une bouchée et cachez-le avant son retour.', detailTagSolo: 'Stratégie solo', detailTagFour: 'Quatre difficultés', detailTagModes: 'Chronométré / infini', detailPlay: 'Jouer sur itch.io ↗', detailPlatform: 'Le jeu s’ouvre sur itch.io ; ce site présente son univers et ses règles.', detailImageAlt: 'Capture de la salle de classe de Classroom Snacks', detailImageCaption: 'Image du jeu',
    howKicker: 'COMMENT JOUER', howTitle: 'Un encas à la fois.', stepOneTitle: 'Choisissez un encas', stepOneBody: 'Chaque encas demande un temps différent et apporte satiété et points.', stepTwoTitle: 'Attendez une ouverture', stepTwoBody: 'Surveillez la position et le regard du professeur. Vous pouvez vous arrêter à mi-chemin.', stepThreeTitle: 'Cachez-le à temps', stepThreeBody: 'En mode chronométré, atteignez la satiété visée et tenez jusqu’à la sonnerie.',
    modesKicker: 'DEUX MODES', modesTitle: 'Finir le cours ou battre un record ?', timedTitle: 'Défi chronométré', timedBody: 'Mangez à votre faim avant la fin du cours et terminez la manche.', endlessTitle: 'Défi infini', endlessBody: 'Ni limite de temps ni limite d’encas. Jusqu’où monterez-vous ?', modesFoot: 'Chaque mode propose quatre difficultés et conserve ses propres records.',
    boardKicker: 'CLASSEMENT TEST', boardTitle: 'Classement infini', boardIntro: 'Chaque difficulté a son classement. Seuls les scores partagés volontairement y figurent.', boardDisclaimer: 'Top 20 par difficulté. Les scores de test ne sont pas vérifiés contre la triche.', tierNormal: 'Normal', tierAdvanced: 'Avancé', tierHard: 'Difficile', tierHell: 'Enfer', boardPanel: 'INFINI', boardTop20: 'TOP 20', boardRank: 'Rang', boardPlayer: 'Joueur', boardScore: 'Score', boardLoading: 'Chargement du classement…', boardOffline: 'Le classement n’est pas connecté. Les places restent libres.', boardEmpty: 'Aucun score pour le moment. Les premières places sont libres.', boardError: 'Classement indisponible. Les places restent libres.', boardCount: '{count} joueurs classés', footerAll: 'Tous les jeux'
  },
  de: {
    navGames: 'Spiele', navAbout: 'Über uns', navAll: 'Alle Spiele', navHow: 'Spielanleitung', navBoard: 'Endlos-Rangliste', navMain: 'Hauptnavigation', navLanguage: 'Websitesprache', themeDay: '☀ Tag', themeNight: '☾ Nacht',
    homeTitleMeta: 'KNOWHY GAMES · Indie-Spiele', homeDescriptionMeta: 'Entdecke Spiele von KNOWHY GAMES. Erfahre mehr über Classroom Snacks und wo du es spielen kannst.',
    homeEyebrow: 'KNOWHY GAMES / Kleines Spielestudio', homeTitle: 'Kleine Spiele. Große Momente.', homeLead: 'Eine wachsende Sammlung verspielter Welten. Entdecke ein Spiel, lerne seine Geschichte kennen und finde heraus, wo du spielen kannst.', homeExplore: 'Spiele entdecken ↓', homeArtCaption: 'Im Fokus · Classroom Snacks',
    gamesKicker: 'SPIELESAMMLUNG', gamesTitle: 'Spiele entdecken', gameTag: 'Solo · leichte Strategie · Testversion', gameTitle: 'Classroom Snacks', gameDescription: 'Die Schulglocke läutet, die Lehrkraft patrouilliert. Wähle einen Snack, warte auf eine Lücke und verstecke ihn rechtzeitig.', gameMore: 'Spiel ansehen →', catalogNote: 'Weitere KNOWHY-Spiele werden hier erscheinen – jeweils mit eigener Seite und Spiellinks.',
    aboutKicker: 'ÜBER DIE WEBSITE', aboutTitle: 'Ein Zuhause für unsere Spiele.', aboutBody: 'Lerne jedes Spiel hier kennen und öffne den passenden Plattform-Link zum Spielen. Diese Website ist ein Katalog.', footerBack: 'Zurück zu KNOWHY', homeImageAlt: 'Classroom-Snacks-Illustration: Ein Kind nascht heimlich im Klassenzimmer',
    detailTitleMeta: 'Classroom Snacks · KNOWHY GAMES', detailDescriptionMeta: 'Spielanleitung, Modi und Spiellink für Classroom Snacks.',
    detailBack: '← Alle Spiele', detailEyebrow: 'Indie-Spiel · Testversion', detailTitle: 'Classroom Snacks', detailLead: 'Die Lehrkraft dreht sich weg – deine Chance. Wähle einen Snack, nimm einen Bissen und verstecke ihn, bevor sie zurückblickt.', detailTagSolo: 'Solo-Strategie', detailTagFour: 'Vier Schwierigkeitsgrade', detailTagModes: 'Zeit / Endlos', detailPlay: 'Auf itch.io spielen ↗', detailPlatform: 'Das Spiel öffnet sich auf itch.io; hier findest du Infos zum Spiel und zur Steuerung.', detailImageAlt: 'Gameplay-Screenshot aus dem Klassenzimmer von Classroom Snacks', detailImageCaption: 'Echtes Spielbild',
    howKicker: 'SO FUNKTIONIERT ES', howTitle: 'Ein Snack nach dem anderen.', stepOneTitle: 'Snack auswählen', stepOneBody: 'Snacks unterscheiden sich bei Essdauer, Sättigung und Punkten.', stepTwoTitle: 'Auf eine Lücke warten', stepTwoBody: 'Achte auf Position und Blickrichtung der Lehrkraft. Du kannst jederzeit aufhören.', stepThreeTitle: 'Rechtzeitig verstecken', stepThreeBody: 'Im Zeitmodus musst du das Sättigungsziel erreichen und bis zur Glocke durchhalten.',
    modesKicker: 'ZWEI MODI', modesTitle: 'Unterricht schaffen oder Rekord jagen?', timedTitle: 'Zeit-Challenge', timedBody: 'Erreiche das Sättigungsziel vor Unterrichtsende und halte durch.', endlessTitle: 'Endlos-Challenge', endlessBody: 'Keine Zeitgrenze und unbegrenzt Snacks. Wie hoch wird deine Punktzahl?', modesFoot: 'Beide Modi haben vier Schwierigkeitsgrade und getrennte persönliche Bestwerte.',
    boardKicker: 'TEST-RANGLISTE', boardTitle: 'Endlos-Rangliste', boardIntro: 'Jeder Schwierigkeitsgrad hat eine eigene Liste. Nur freiwillig geteilte Punkte erscheinen hier.', boardDisclaimer: 'Top 20 pro Schwierigkeit. Testwerte werden nicht auf Betrug geprüft.', tierNormal: 'Normal', tierAdvanced: 'Komplex', tierHard: 'Schwer', tierHell: 'Hölle', boardPanel: 'ENDLOS', boardTop20: 'TOP 20', boardRank: 'Rang', boardPlayer: 'Spieler', boardScore: 'Punkte', boardLoading: 'Rangliste wird geladen…', boardOffline: 'Rangliste ist nicht verbunden. Plätze bleiben frei.', boardEmpty: 'Noch keine Einträge. Die ersten Plätze sind frei.', boardError: 'Rangliste derzeit nicht erreichbar. Plätze bleiben frei.', boardCount: '{count} Spieler in der Rangliste', footerAll: 'Alle Spiele'
  }
};

const releaseCopy = {
  en: ['Platforms and release status', 'Playtest on Playgama ↗', 'Updated browser version available.', 'Public playtest available; formal catalog certification is pending.', 'Submitted on October 1, 2026; awaiting review.', 'Release is pending filing access; a support ticket has been submitted.'],
  'zh-CN': ['平台与发布状态', '前往 Playgama 试玩 ↗', '新版浏览器游戏已更新。', '公开试玩已更新；正式平台入驻尚待认证。', '已于 2026 年 10 月 1 日提交，等待审核。', '发布尚待备案通道开通，已提交工单。'],
  ja: ['配信先と公開状況', 'Playgama で試遊 ↗', 'ブラウザー版を更新しました。', '公開テスト版を更新済み。正式掲載の認証は未完了です。', '2026年10月1日に申請済み。審査待ちです。', '公開に必要な登録手続きの受付待ちです。問い合わせを提出済みです。'],
  ko: ['플랫폼 및 출시 상태', 'Playgama에서 체험 ↗', '브라우저 버전이 업데이트되었습니다.', '공개 체험판이 업데이트되었습니다. 정식 등록 인증은 대기 중입니다.', '2026년 10월 1일 제출, 심사 대기 중입니다.', '출시에 필요한 등록 절차의 개통을 기다리고 있습니다. 문의를 제출했습니다.'],
  es: ['Plataformas y estado de publicación', 'Probar en Playgama ↗', 'Versión para navegador actualizada.', 'Prueba pública actualizada; la certificación del catálogo está pendiente.', 'Enviado el 1 de octubre de 2026; pendiente de revisión.', 'Pendiente de acceso al registro necesario para publicar; consulta enviada.'],
  'pt-BR': ['Plataformas e situação do lançamento', 'Testar no Playgama ↗', 'Versão para navegador atualizada.', 'Teste público atualizado; certificação do catálogo pendente.', 'Enviado em 1 de outubro de 2026; aguardando análise.', 'Aguardando acesso ao registro necessário para publicar; solicitação enviada.'],
  fr: ['Plateformes et état de publication', 'Tester sur Playgama ↗', 'Version navigateur mise à jour.', 'Test public mis à jour ; certification du catalogue en attente.', 'Soumis le 1er octobre 2026 ; en attente de validation.', 'Accès à la procédure de déclaration nécessaire à la publication en attente ; demande envoyée.'],
  de: ['Plattformen und Veröffentlichungsstatus', 'Auf Playgama testen ↗', 'Browserversion aktualisiert.', 'Öffentlicher Test aktualisiert; Zertifizierung für den Katalog steht aus.', 'Am 1. Oktober 2026 eingereicht; Prüfung ausstehend.', 'Freischaltung des erforderlichen Registrierungsverfahrens steht aus; Supportanfrage eingereicht.']
};
const additionalReleaseCopy = {
  en: ['Build uploaded; test ad completed. Publishing verification remains pending.', 'Developer access requested; awaiting a response. Not yet released.'],
  'zh-CN': ['游戏包已上传，测试广告已完整播放；发布验证仍待解锁。', '开发者准入申请已提交，等待回复；尚未上架。'],
  ja: ['アップロード済み。テスト広告は再生完了。公開の検証は未完了です。', '開発者登録を申請済み。返信待ち。まだ公開されていません。'],
  ko: ['업로드 완료. 테스트 광고 재생 완료. 출시 검증은 대기 중입니다.', '개발자 접근 신청 완료. 답변 대기 중이며 아직 출시되지 않았습니다.'],
  es: ['Juego subido; anuncio de prueba completado. Verificación de publicación pendiente.', 'Acceso de desarrollador solicitado; esperando respuesta. Aún no publicado.'],
  'pt-BR': ['Jogo enviado; anúncio de teste concluído. Verificação de publicação pendente.', 'Acesso de desenvolvedor solicitado; aguardando resposta. Ainda não lançado.'],
  fr: ['Jeu téléversé ; publicité de test terminée. Validation de publication en attente.', 'Accès développeur demandé ; réponse en attente. Pas encore publié.'],
  de: ['Spiel hochgeladen; Testanzeige abgeschlossen. Veröffentlichungsprüfung ausstehend.', 'Entwicklerzugang beantragt; Antwort ausstehend. Noch nicht veröffentlicht.']
};
for (const locale of SUPPORTED_LOCALES) {
  const [releaseTitle, detailPlayPlaygama, itchStatus, playgamaStatus, crazygamesStatus, taptapStatus] = releaseCopy[locale];
  Object.assign(translations[locale], { releaseTitle, detailPlayPlaygama, itchStatus, playgamaStatus, crazygamesStatus, taptapStatus });
  const [gamemonetizeStatus, pokiStatus] = additionalReleaseCopy[locale];
  Object.assign(translations[locale], { gamemonetizeStatus, pokiStatus });
}

export function resolveLocale(saved, browser) {
  if (SUPPORTED_LOCALES.includes(saved)) return saved;
  return 'en';
}

export function translate(locale, key, params = {}) {
  const template = (translations[locale] || translations.en)[key] ?? translations.en[key] ?? key;
  return template.replace(/\{(\w+)\}/g, (_, name) => String(params[name] ?? ''));
}
